# fly.toml app configuration file generated for dormitory-backend on 2025-07-22T05:02:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dormitory-backend'
primary_region = 'hkg'

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

# [mounts]
#   source = "gubkin_uploads"
#   destination = "/app/uploads"
